name: bathao
description: "Bathao App"
publish_to: none
version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2  # stable
  linear_progress_bar: ^1.2.0

  # ZEGO (full features)
  zego_uikit: ^2.28.23
  zego_uikit_prebuilt_call: ^4.22.1
  zego_uikit_signaling_plugin: ^2.8.19

  # Optional small UI helper
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/stickers/
